version: "3.9"

services:
  # nextjs:
  #   build: .
  #   container_name: nextjs_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mariadb
  #   environment:
  #     DATABASE_URL: "mysql://root:password@mariadb:3306/dashboard_db"

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ns_root_5769
      MYSQL_DATABASE: ns_db
      MYSQL_USER: ns_user
      MYSQL_PASSWORD: ns_u_root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DEFAULT_DB=ns_db
      - ADMINER_DEFAULT_USERNAME=root
      - ADMINER_DEFAULT_PASSWORD=ns_root_5769
    ports:
      - "8080:8080"

volumes:
  mariadb_data:
