import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import "@/assets/styles/tailwindGeneral.css";
import MainHeader from "@/components/ui/MainHeader";
import MainFooter from "@/components/ui/MainFooter";
import { ToastifyProvider } from "@/components/providers/ToastifyProvider";
import localFont from "@next/font/local";

const font = localFont({
  src: "@/assets/fonts/irsans.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <MainHeader />
      <html lang="en">
        <body className={`antialiased rtl`}>
          <main className="container">{children}</main>
          <ToastifyProvider />
        </body>
      </html>
      <MainFooter />
    </>
  );
}
